### ISSUE TITLE
First time run immediately crashes

### ISSUE THREAD

**Issue by johnmcdowall** [joshmn/ahoy_captain#36]
Just installed the gem, and I do have some events to show: 

But the dashboard shows up with some placeholder skeletons, then immediately crashes:

<img width="1016" alt="Screenshot 2023-11-01 at 21 09 20" src="https://github.com/joshmn/ahoy_captain/assets/237175/ad1fd7e7-e48b-4fb2-bce1-784e6a2d9c8d">

I can circumvent the crash by adding `return 0 if value.current.nil? || value.compared_to.nil?` before the diff calculation. Happy to open a PR unless you want the comparable itself to have safer logic.

**Comment by johnmcdowall** [comment]
Seems fixed now.

**Comment by abuisman** [comment]
Sadly I have this error now too. 

I've created a fork to include the latest version and the fix for the shims described here: https://github.com/joshmn/ahoy_captain/pull/40

I have more than 1000 events in my database that should be eligible.
