### ISSUE TITLE
Ahoy captain not recognizing data or failing to initialize

### ISSUE THREAD

**Issue by oyenmwen** [joshmn/ahoy_captain#6]
Hi I have a rails 7 esbuild app and am trying to get it to work with `ahoy_captain`. When I visit `/ahoy_captain`, I do not get any results: 

![img](https://i.imgur.com/2X0H2WV.png)

I also get this error and other warnings in the console: 

![img](https://i.imgur.com/DxnEaT4.png)

I followed the installation instructions to the tee (although, `rails g ahoy_captain:migration` does not work). 

I also checked that `ahoy_visits` table has data

Any help is appreciated!

**Comment by joshmn** [comment]
What happens if you select a period like year-to-date? What happens if you try to fetch the data using ActiveRecord based on the queries its reporting?

http://localhost:3000/ahoy_captain?period=ytd should get you there quick.

**Comment by oyenmwen** [comment]
Same results come up. Here are the logs for it:

```
17:24:03 web.1  | Processing by AhoyCaptain::Stats::UniqueVisitorsController#index as HTML
17:24:03 web.1  |   Parameters: {"period"=>"ytd"}
17:24:03 web.1  |   Ahoy::Visit Count (0.9ms)  SELECT COUNT(DISTINCT "ahoy_visits"."id") AS "count_id", DATE_TRUNC('day', "ahoy_visits"."started_at"::timestamptz AT TIME ZONE 'Etc/UTC')::date AS "date_trunc_day_ahoy_visits_started_at_timestamptz_at_time_zone_" FROM "ahoy_visits" LEFT OUTER JOIN "ahoy_events" ON "ahoy_events"."visit_id" = "ahoy_visits"."id" WHERE ("ahoy_visits"."started_at" > '2023-01-01 00:00:00' AND "ahoy_visits"."started_at" < '2023-08-03 21:24:03.807444' AND "ahoy_events"."time" > '2023-01-01 00:00:00' AND "ahoy_events"."time" < '2023-08-03 21:24:03.807502') AND ("ahoy_visits"."started_at" IS NOT NULL) GROUP BY DATE_TRUNC('day', "ahoy_visits"."started_at"::timestamptz AT TIME ZONE 'Etc/UTC')::date /*application:Blens,controller:unique_visitors,action:index*/
17:24:03 web.1  |   Rendering layout ...
17:24:03 web.1  |   Rendering ...
17:24:03 web.1  |   Rendered .... (Duration: 0.2ms | Allocations: 119)
17:24:03 web.1  |   Rendered layout .... (Duration: 58.9ms | Allocations: 50800)
17:24:03 web.1  | Completed 200 OK in 66ms (Views: 59.5ms | ActiveRecord: 0.9ms | Allocations: 54561)
17:24:03 web.1  | 

```

When I try the query using Active Record I actually get no results as well. I think its because of my ahoy_events table is empty. So i guess I need to track events as well. Thought it could work with visits only.

Removing the left outer join of `ahoy_events` does return results though...

```
SELECT COUNT(DISTINCT "ahoy_visits"."id") AS "count_id", 
         DATE_TRUNC('day', "ahoy_visits"."started_at"::timestamptz AT TIME ZONE 'Etc/UTC')::date 
       AS "date_trunc_day_ahoy_visits_started_at_timestamptz_at_time_zone_" 
FROM "ahoy_visits"
WHERE ("ahoy_visits"."started_at" > '2023-01-01 00:00:00' 
        AND "ahoy_visits"."started_at" < '2023-08-03 21:24:03.807444' 
        AND "ahoy_visits"."started_at" IS NOT NULL
       ) 
GROUP BY DATE_TRUNC('day', "ahoy_visits"."started_at"::timestamptz AT TIME ZONE 'Etc/UTC')
```

While with `ahoy_events` return 0 results
```
SELECT COUNT(DISTINCT "ahoy_visits"."id") AS "count_id", 
       DATE_TRUNC('day', "ahoy_visits"."started_at"::timestamptz AT TIME ZONE 'Etc/UTC')::date AS "date_trunc_day_ahoy_visits_started_at_timestamptz_at_time_zone_" 
FROM "ahoy_visits" LEFT OUTER JOIN "ahoy_events" 
ON "ahoy_events"."visit_id" = "ahoy_visits"."id" 
WHERE ("ahoy_visits"."started_at" > '2023-01-01 00:00:00' AND "ahoy_visits"."started_at" < '2023-08-03 21:24:03.807444' 
    AND "ahoy_events"."time" > '2023-01-01 00:00:00' 
    AND "ahoy_events"."time" < '2023-08-03 21:24:03.807502') 
    AND ("ahoy_visits"."started_at" IS NOT NULL) 
GROUP BY DATE_TRUNC('day', "ahoy_visits"."started_at"::timestamptz AT TIME ZONE 'Etc/UTC')
```

What are my paths forward?

**Comment by davidalejandroaguilar** [comment]
Same thing happened to me. I just pointed the gem to the `main` branch (since there was no release yesterday) and it's fixed there. Try the 0.8 release and see if it goes away.

**Comment by oyenmwen** [comment]
Yes that helped, thanks so much. Still get the NaN as well

**Comment by joshmn** [comment]
@oyenmwen should be fixed in 0.81 which was just released.

there's a fix for queries coming up here shortly. just need to figure out why some are misbehaving.

**Comment by joshmn** [comment]
@oyenmwen give 0.82 a try. lots of query fixes.

**Comment by davidalejandroaguilar** [comment]
I'm not getting data on 0.83, yet I do when I'm on 0.8.

I have only tested in localhost, though I don't see any code that filters that.

## 0.8

<img width="1723" alt="image" src="https://github.com/joshmn/ahoy_captain/assets/15317732/2f636df6-87c0-479a-9167-767421ed4ff6">

### Query

```rb
23:00:03 web.1             | Started GET "/ahoy_captain/stats/unique_visitors?period=all" for 127.0.0.1 at 2023-08-07 23:00:03 -0700
23:00:03 web.1             | Processing by AhoyCaptain::Stats::UniqueVisitorsController#index as HTML
23:00:03 web.1             |   Parameters: {"period"=>"all"}
23:00:03 web.1             |   Ahoy::Visit Count (1.2ms)  SELECT COUNT(DISTINCT "ahoy_visits"."visitor_token") AS "count_visitor_token", DATE_TRUNC('month', "ahoy_visits"."started_at"::timestamptz AT TIME ZONE 'Etc/UTC')::date AS "date_trunc_month_ahoy_visits_started_at_timestamptz_at_time_zon" FROM "ahoy_visits" LEFT OUTER JOIN "ahoy_events" ON "ahoy_events"."visit_id" = "ahoy_visits"."id" WHERE (("ahoy_visits"."started_at" > '2004-08-01 00:00:00' AND "ahoy_visits"."started_at" < '2023-08-08 06:00:03.948980') OR ("ahoy_events"."time" > '2004-08-01 00:00:00' AND "ahoy_events"."time" < '2023-08-08 06:00:03.949274')) AND ("ahoy_visits"."started_at" IS NOT NULL) GROUP BY DATE_TRUNC('month', "ahoy_visits"."started_at"::timestamptz AT TIME ZONE 'Etc/UTC')::date
```

## 0.83

<img width="1728" alt="image" src="https://github.com/joshmn/ahoy_captain/assets/15317732/0e4a3b44-94d7-452f-9e85-aa007020b594">

### Query

```rb
23:02:43 web.1             | Started GET "/ahoy_captain/?period=all" for 127.0.0.1 at 2023-08-07 23:02:43 -0700
23:02:43 web.1             | Processing by AhoyCaptain::Stats::UniqueVisitorsController#index as HTML
23:02:43 web.1             |   Parameters: {"period"=>"all"}
23:02:43 web.1             |   Ahoy::Visit Count (0.8ms)  SELECT COUNT(DISTINCT "ahoy_visits"."visitor_token") AS "count_visitor_token", DATE_TRUNC('month', "ahoy_visits"."started_at"::timestamptz AT TIME ZONE 'Etc/UTC')::date AS "date_trunc_month_ahoy_visits_started_at_timestamptz_at_time_zon" FROM "ahoy_visits" LEFT OUTER JOIN "ahoy_events" ON "ahoy_events"."visit_id" = "ahoy_visits"."id" WHERE ("ahoy_visits"."started_at" > '2004-08-01 00:00:00' AND "ahoy_visits"."started_at" < '2023-08-08 06:02:43.956371') AND ("ahoy_events"."time" > '2004-08-01 00:00:00' AND "ahoy_events"."time" < '2023-08-08 06:02:43.956679') AND ("ahoy_visits"."started_at" IS NOT NULL) GROUP BY DATE_TRUNC('month', "ahoy_visits"."started_at"::timestamptz AT TIME ZONE 'Etc/UTC')::date
```

**Comment by joshmn** [comment]
Are your page view events setup correctly?

**Comment by davidalejandroaguilar** [comment]
@joshmn Thanks for your response, no I don't have page view events set up since there was no mention of that on the `ahoy` repo or the `ahoy_captain` one. I now see that https://github.com/joshmn/ahoy_captain/commit/e7ad0c60ba1902d9ab0ba514e02097e21bb4e360 added clarification, however, I think this is not clear:

>By default, AhoyCaptain assumes you're tracking `controller` and `action` in your `Ahoy::Event` properties, and a page view event is named `$view`.

I _assumed_ it means `ahoy_captain` expect us to track all actions [like this section in the ahoy readme does](https://github.com/ankane/ahoy#events). Something like:

```rb
class ApplicationController < ActionController::Base
  after_action :track_page_view

  protected

  def track_page_view
    ahoy.track "$view", controller: controller_name, action: action_name, url: request.url, params: request.path_parameters
  end
end
```

If so, it'd probably be good to add the above snippet to the README, or inject it via a generator. In addition, these configs should probably be enabled by default, in order to provide good, batteries included defaults:

```rb
config.event.url_column = "properties->>'url'"
config.event.url_exists = "JSONB_EXISTS(properties, 'controller') AND JSONB_EXISTS(properties, 'action')"
```

I tested the above and it works great!

**Comment by joshmn** [comment]
@davidalejandroaguilar how's this? https://github.com/joshmn/ahoy_captain/commit/f8246fcc8520088d9d495e310c134331d31cf455 :)

**Comment by davidalejandroaguilar** [comment]
That works, thank you very much for your time in both responding and building this gem 😺

**Comment by oyenmwen** [comment]
So my problem was that I wasnt tracking actions with ahoy events. Worked once i added that. Thanks!
